version: 2

jobs:
  build: 
    docker: 
      - image: circleci/node:8.9.4
    steps:
      - checkout

      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
  unit-test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
        key: v1-node-modules-cache-{{ checksum "package.json" }}
      - run: 
          name: Run unit tests
          command: npm run test:unit
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build


      